--1.Select title, description from film;
--2.select * from film
--where length > 60 and length <75;
--3.SELECT * FROM film
--WHERE rental_rate=0.99 AND replacement_cost=12.99 OR replacement_cost=28.99;
--4.select first_name,last_name from customer
--where first_name='Mary';
--5.select * from  film
--where not length >50 and not (rental_rate=2.99 or rental_rate=4.99);
